#!/bin/sh
set -x
set -e

echo "--- Starting package.sh ---"

echo "// swift-tools-version: 5.9" > Package.swift
echo "// This file is auto-generated. Do not edit this file directly. Instead, make changes in \`Package/\` directory and then run \`package.sh\` to generate a new \`Package.swift\` file." >> Package.swift
cat Package/Support/*.swift >> Package.swift
cat Package/Sources/**/*.swift >> Package.swift
cat Package/Sources/*.swift >> Package.swift

echo "--- Generated Package.swift content: ---"
cat Package.swift
echo "-----------------------------"

# Check for the resources line:
if grep -q "Resource.copy(\"Resources/MochiSchema.xcdatamodeld\")" Package.swift; then
  echo "Resource line found in Package.swift"
else
  echo "ERROR: Resource line NOT found in Package.swift"
  exit 1  # Exit with an error to fail the workflow
fi

# Check if Package.swift is empty
if [ -s "Package.swift" ]; then
    echo "Package.swift is not empty"
else
    echo "ERROR: Package.swift is empty"
    exit 1
fi

echo "--- package.sh completed successfully ---"
